-- Unknown specifications must remain NULL instead of becoming a negative answer.
-- Existing values are preserved; previously collected products need to be reviewed.
ALTER TABLE "especificacoes_notebooks"
  ALTER COLUMN "gpu_integrada" DROP NOT NULL,
  ALTER COLUMN "gpu_integrada" DROP DEFAULT,
  ALTER COLUMN "gpu_dedicada" DROP NOT NULL,
  ALTER COLUMN "gpu_dedicada" DROP DEFAULT,
  ALTER COLUMN "upgrade_ram" DROP NOT NULL,
  ALTER COLUMN "upgrade_ram" DROP DEFAULT,
  ALTER COLUMN "upgrade_armazenamento" DROP NOT NULL,
  ALTER COLUMN "upgrade_armazenamento" DROP DEFAULT,
  ALTER COLUMN "touch" DROP NOT NULL,
  ALTER COLUMN "touch" DROP DEFAULT,
  ALTER COLUMN "usb_a" DROP NOT NULL,
  ALTER COLUMN "usb_a" DROP DEFAULT,
  ALTER COLUMN "usb_c" DROP NOT NULL,
  ALTER COLUMN "usb_c" DROP DEFAULT,
  ALTER COLUMN "thunderbolt" DROP NOT NULL,
  ALTER COLUMN "thunderbolt" DROP DEFAULT,
  ALTER COLUMN "hdmi" DROP NOT NULL,
  ALTER COLUMN "hdmi" DROP DEFAULT,
  ALTER COLUMN "display_port" DROP NOT NULL,
  ALTER COLUMN "display_port" DROP DEFAULT,
  ALTER COLUMN "ethernet" DROP NOT NULL,
  ALTER COLUMN "ethernet" DROP DEFAULT,
  ALTER COLUMN "leitor_cartao" DROP NOT NULL,
  ALTER COLUMN "leitor_cartao" DROP DEFAULT,
  ALTER COLUMN "webcam" DROP NOT NULL,
  ALTER COLUMN "webcam" DROP DEFAULT,
  ALTER COLUMN "teclado_iluminado" DROP NOT NULL,
  ALTER COLUMN "teclado_iluminado" DROP DEFAULT,
  ALTER COLUMN "teclado_numerico" DROP NOT NULL,
  ALTER COLUMN "teclado_numerico" DROP DEFAULT,
  ALTER COLUMN "leitor_digital" DROP NOT NULL,
  ALTER COLUMN "leitor_digital" DROP DEFAULT;
